name: fwfh_benchmark
publish_to: none
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.32.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core:
    path: ../packages/core
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
flutter:
  assets:
    - fixtures/
