include: package:lint/analysis_options_package.yaml

analyzer:
  errors:
    todo: info

linter:
  rules:
    always_put_control_body_on_new_line: true

    # relative vs. package imports
    always_use_package_imports: false
    avoid_relative_lib_imports: true
    prefer_relative_imports: true
