env:
  CODECOV_TOKEN: ENCRYPTED[0bad38cf59a2fda73e72491e18a564995cf3a5c862b5400834bfa9873713e780a2deed3e57b265279bd1e91168ee492a]

unit_test_task:
  container:
    image: cirrusci/flutter
  test_script: COVERAGE=1 ./tool/test.sh
  codecov_script: bash <(curl -s https://codecov.io/bash)

ios_test_task:
  skip: "!changesInclude('lib/src/web_view.dart')"
  osx_instance:
    image: mojave-xcode-11.2.1-flutter
  setup_script: xcrun simctl create iPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro-Max com.apple.CoreSimulator.SimRuntime.iOS-13-2 | xargs xcrun simctl boot
  test_script: ./tool/integration.sh

android_test_task:
  skip: "!changesInclude('lib/src/video_player.dart', 'lib/src/web_view.dart')"
  container:
    image: cirrusci/flutter
  env:
    AWS_ACCESS_KEY_ID: ENCRYPTED[bfad5318e7b922be21065747210e175bff4a016be7b7f32d0e34a5e7c145ac5c685088a16a28488f76259b07bf960e8a]
    AWS_DEFAULT_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[c2e879143bcfa89be383584812034fbef751beb2968629aaef34e427dc834a88cbeb953152d660fd243d8b1018c4c771]
  test_script: ./tool/sylph/cmd.sh
