env:
  CODECOV_TOKEN: ENCRYPTED[0bad38cf59a2fda73e72491e18a564995cf3a5c862b5400834bfa9873713e780a2deed3e57b265279bd1e91168ee492a]

unit_test_task:
  container:
    image: cirrusci/flutter
  pub_cache:
    folder: ~/.pub-cache
  test_script: COVERAGE=1 ./tool/test.sh
  codecov_script: bash <(curl -s https://codecov.io/bash)
