coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0.5%
    patch:
      default:
        target: 80%

ignore:
  - "packages/enhanced/lib/src/widgets/video_player.dart"
  - "packages/enhanced/lib/src/widgets/web_view"
