coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0.5%
    patch:
      default:
        target: 80%

ignore:
  - "demo_app"
  - "packages/enhanced/lib/src/external/"
  - "packages/enhanced/lib/src/widgets/video_player.dart"
  - "packages/fwfh_webview/lib/src/web_view/"
