name: fwfh_chewie
version: 0.16.1
description: WidgetFactory extension to render VIDEO with the chewie plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=3.44.0"
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  chewie: ^1.16.2
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ">=0.14.2 <0.18.0"
  video_player: ^2.14.0

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
  plugin_platform_interface: any
  video_player_platform_interface: ^6.9.0

funding:
  - https://www.patreon.com/daohoangson
  - https://buymeacoffee.com/daohoangson

topics:
  - video
  - fwfh
