include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    # TODO: investigate `include_file_not_found` warning
    - example

linter:
  rules:
    missing_whitespace_between_adjacent_strings: false
