flowchart TD
    _addBitsFromNode[/process DOM element/]
        --> ifIsText{plain\ntext?}
        -->|yes| bitOK( )

    ifIsText
        -->|no| ifCustomWidget{custom\nwidget?}
        -->|yes\n\ncustomWidgetBuilder| ifIsInlineCustomWidget{inline\nwidget?}
        --->|no| appendWidgetBitBlock[/render\nblock widget/]
        ---> bitOK
    
    ifIsInlineCustomWidget
        -->|yes\n\nInlineCustomWidget| flattener
        -->|onRenderInline| RichText[/render\nRichText/]
        --> bitOK

    ifCustomWidget
        -->|no| _parseEverything[parser]
        -->|WidgetFactory.parse\n\ndefaultStyles\n\ncustomStylesBuilder| _parseOK( )
        ~~~ _addBitsFromNodeOK

    _parseOK
        -.->|process children\nelements recursively| _addBitsFromNode
        -.->|onVisitChild| _addBitsFromNodeOK( )
        -->|onParsed| ifIsBlock{block\nelement?}
        -->|no| flattener

    ifIsBlock
        --->|yes\n\nonRenderBlock| appendBuiltSubTree[/render block/]
        ---> bitOK
