name: fwfh_form
version: 0.16.0
description: WidgetFactory extension to render simple FORM elements.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=3.10.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ">=0.8.0 <0.17.0"

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any

funding:
  - https://patreon.com/daohoangson
  - https://buymeacoffee.com/daohoangson

topics:
  - fwfh
