name: Flutter@dev
on:
  push:
    branches:
      - release/dev
  pull_request:
    branches:
      - release/dev

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: dev
      - run: ./tool/test.sh
