name: Flutter@beta
on:
  push:
    branches:
      - release/beta
  pull_request:
    branches:
      - release/beta

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    env:
      GOLDEN_SKIP: "yes"
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: beta
      - run: ./tool/test.sh
