name: fwfh_text_style
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        channel:
          - beta
          - dev

    # Run these tests on PRs against the `master` branch.
    # In case one of these fails, create a new PR against `beta` or `dev` branch
    # and publish a new beta/dev version to make sure there is a compatible version
    # of `fwfh_text_style` for all active Flutter versions.
    name: Test on ${{ matrix.channel }} channel
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: packages/fwfh_text_style
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}
      - run: flutter --version
      - run: flutter analyze
      - run: flutter test
